namespace ArrowverseBot
{
    static class ImageFetcher
    {
        static public string[] Harry =
        {
         "https://i.imgur.com/e1OjqO1g.png",
         "https://i.imgur.com/zdEjTDO.png",
         "https://i.imgur.com/nCUaAPs.jpg",
         "https://i.imgur.com/E5SGrpj.png"
        };

        static public string[] Killers =
        {
            "Trapper",
            "Wraith",
            "Hillbilly",
            "Nurse",
            "Hunteress",
            "Myers",
            "Hag",
            "Doctor",
            "Leatherface/Bubba",
            "Freddy",
            "Pig",
            "Clown",
            "Spirit",
            "Legion",
            "Plague",
            "Ghostface",
            "Demogorgon",
            "Oni",
            "Gunslinger",
            "Pyramid Head",
            "Blight",
            "Twins"
        };

        static public string[] SPerks =
        {
            "Ace in the Hole",
            "Adrenaline",
            "Aftercare",
            "Alert",
            "Any Means Necessary",
            "Appraisal",
            "Autodidact",
            "Babysitter",
            "Balanced Landing",
            "Better Together",
            "Blood Pact",
            "Boil Over",
            "Bond",
            "Borrowed Time",
            "Botany Knowledge",
            "Breakdown",
            "Breakout",
            "Buckle Up",
            "Built to Last",
            "Calm Spirit",
            "Camaraderie",
            "Dance With Me",
            "Dark Sense",
            "Dead Hard",
            "Deception",
            "Decisive Strike",
            "Deja Vu",
            "Deliverance",
            "Desperate Measures",
            "Detective's Hunch",
            "Distortion",
            "Diversion",
            "Empathy",
            "Fixated",
            "Flip-Flop",
            "For the People",
            "Head On",
            "Hope",
            "Inner Strength",
            "Iron Will",
            "Kindred",
            "Leader",
            "Left Behind",
            "Lightweight",
            "Lithe",
            "Lucky Break",
            "Mettle of Man",
            "No Mither",
            "No One Left Behind",
            "Object of Obsession",
            "Off the Record",
            "Open-Handed",
            "Pharmacy",
            "Plunder's Instinct",
            "Poised",
            "Power Struggle",
            "Premonition",
            "Prove Thyself",
            "Quick & Quiet",
            "Red Herring",
            "Repressed Alliance",
            "Resilience",
            "Saboteur",
            "Second Wind",
            "Self-Care",
            "Slippery Meat",
            "Small Game",
            "Sole Survivor",
            "Solidarity",
            "Soul Guard",
            "Spine Chill",
            "Sprint Burst",
            "Stake Out",
            "Streetwise",
            "Technician",
            "Tenacity",
            "This Is Not Happening",
            "Up the Ante",
            "Unbreakable",
            "Urban Evasion",
            "Vigil",
            "Visionary",
            "Wake Up!",
            "We'll Make It",
            "We're Gonna Live Forever",
            "Windows of Opportunity"
        };

        static public string[] KPerks =
        {
            "A Nurse's Calling",
            "Agitation",
            "Bamboozle",
            "Barbecue & Chilli",
            "Beat of Prey",
            "Bitter Murmur",
            "Blood Echo",
            "Blood Warden",
            "Bloodhound",
            "Brutal Strength",
            "Corrupt Intervention",
            "Coulrophobia",
            "Coup de Grace",
            "Cruel Limits",
            "Dark Devotion",
            "Dead Man's Switch",
            "Deathbound",
            "Deerstalker",
            "Discordance",
            "Distressing",
            "Dragon's Grip",
            "Dying Light",
            "Enduring",
            "Fire Up",
            "Forced Penance",
            "Franklin's Demise",
            "Furtive Chase",
            "Gearhead",
            "Hangman's Trick",
            "Hex: Blood Favour",
            "Hex: Devour Hope",
            "Hex: Haunted Ground",
            "Hex: Huntress Lullaby",
            "Hex: No One Escapes Death",
            "Hex: Retribution",
            "Hex: Ruin",
            "Hex: The Third Seal",
            "Hex: Thrill Of The Hunt",
            "Hex: Undying",
            "Hoarder",
            "I'm All Ears",
            "Infectious Fright",
            "Insidious",
            "Iron Grasp",
            "Iron Maiden",
            "Knock Out",
            "Lightborn",
            "Mad Grit",
            "Make Your Choice",
            "Mindbreaker",
            "Monitor & Abuse",
            "Monstrous Shrine",
            "Nemesis",
            "Oppression",
            "Overcharge",
            "Overwhelming Presence",
            "Play With Your Food",
            "Pop Goes The Weasel",
            "Predator",
            "Rancor",
            "Remember Me",
            "Save The Best For Last",
            "Shadowborn",
            "Sloppy Butcher",
            "Spies From The Shadows",
            "Spirit Fury",
            "Stridor",
            "Surge",
            "Surveillance",
            "Territorial Imperative",
            "Thanatophobia",
            "Thrilling Tremors",
            "Tinkerer",
            "Trail of Torment",
            "Unnerving Presence",
            "Unrelenting",
            "Whispers",
            "Zanshin Tatics"
        };
    }
}
